### ISSUE TITLE
怎么获得直播间的用户头像呢？

### ISSUE THREAD

**Issue by a576435459** [zhonghangAlex/DySpider#2]
怎么获得直播间的用户头像呢？

**Comment by LvLH** [comment]
> 怎么获得直播间的用户头像呢？

解析里面的img即可

**Comment by Jehuty-ML** [comment]
> 怎么获得直播间的用户头像呢？

你运行正常获取弹幕那些吗？

**Comment by Iwty** [comment]
你好 运行出现这个错误怎么修改呢 Handshake status 200 OK

**Comment by zhonghangAlex** [comment]
暂时还没有研究，我现在主要做数据分析这块的内容，我的数据目前不涉及头像，回头有机会研究一下
