### ISSUE TITLE
spider.py第42行少替换了一个直播间id,以及运行项目报ssl错误的问题。

### ISSUE THREAD

**Issue by GodBlessNoBugs** [zhonghangAlex/DySpider#4]
项目clone下来之后，spider.py文件第42行，生成wss地址，要替换两处直播间id，代码中只替换了一处。修改完之后运行代码，报ssl错误。[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)。

**Comment by GodBlessNoBugs** [comment]
已经解决问题了，貌似是因为wss地址更新的问题，在浏览器里随便找个直播间用F12找到wss地址，替换spider.py里的第42行就行了，关于ssl问题可以在spider.py的第127行替换成这个：        ws.run_forever(sslopt={"cert_reqs":ssl.CERT_NONE})，再导入一下ssl库就ok了。

**Comment by zhonghangAlex** [comment]
是的，之前也有人问过这块
